Repository u-motion/u-words, pull requests merged in 2020-10, with the labels that each got.

#1 スタイルガイドの自己矛盾を修復
  README.md
Labels: README 修正

#2 csvlint 導入
  .github/workflows/csvlint.yml
  README.md
Labels: README 修正

#4 csvlint のジョブ名を「Build」から「CSV構文チェック」に変更
  .github/workflows/csvlint.yml
Labels: README 修正

#3 「搾乳ロボット」を追加
  words.csv
Labels: 追加

#5 「個体識別番号」、「品種」など5項目を追加
  README.md
  words.csv
Labels: 追加

#6 説明に関するスタイルガイドを追記
  README.md
  words.csv
Labels: README 修正

#7 牛海綿状脳症、起立困難、動物福祉、不快指数、豚熱を追加
  words.csv
Labels: 追加

#8 説明文を短縮
  words.csv
Labels: 記述改良

#9 スタイルガイドに別名が複数ある場合の記法を追記
  README.md
Labels: スタイルガイド
